export * from "./Main/Main";
export * from "./Authorization/Authorization";
export * from "./Registration/Registration";
export * from "./Timer/Timer";
export * from "./Projects/Projects";
export * from "./Project/Project";
export * from "./Analytics/Analytics";
export * from "./Profile/Profile";
export * from "./404/404.jsx";
