export const ACTION_TYPE = {
	SET_USER: "SET_USER",
	SET_PROJECT_DATA: "SET_PROJECT_DATA",
	RESET_PROJECT_DATA: "RESET_PROJECT_DATA",
	LOGOUT: "LOGOUT",
	OPEN_MODAL: "OPEN_MODAL",
	CLOSE_MODAL: "CLOSE_MODAL",
	ADD_TASK: "ADD_TASK",
	REMOVE_TASK: "REMOVE_TASK",
	SET_TAGS_DATA: "SET_TAGS_DATA",
};
